name: Validate Student PR

on:
  pull_request:
    branches:
      - lesson-complete

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Echo PR SHA
        run: echo "this has changed in the forked repo"
